In [1]:
import pandas as pd
import numpy as np

In [2]:
fn = "../data/IDX/AX_stab_pool/generated_SRM_table.csv"
data = pd.read_csv(fn)
data

,Unnamed: 0,Unnamed: 0.1,Name,mz,rt_start,rt_end,Charge,Product mz,CE,Normalized Intensity
0,0,4,Compound 5,162.112534,5.335723,5.680650,1,103.04,16.397564,5.217794e+06
1,1,4,Compound 5,162.112534,5.335723,5.680650,1,60.08,16.397564,4.085165e+06
2,2,4,Compound 5,162.112534,5.335723,5.680650,1,85.03,16.397564,2.510912e+06
3,3,4,Compound 5,162.112534,5.335723,5.680650,1,102.09,16.397564,1.756255e+06
4,4,4,Compound 5,162.112534,5.335723,5.680650,1,58.07,36.804199,1.659919e+06
...,...,...,...,...,...,...,...,...,...,...
3738,3738,618,Compound 614,199.170425,0.698493,0.914036,-1,119.05,21.467686,6.778207e+04
3739,3739,618,Compound 614,199.170425,0.698493,0.914036,-1,93.03,37.792993,8.675127e+03
3740,3740,618,Compound 614,199.170425,0.698493,0.914036,-1,79.96,29.630339,4.840894e+03
3741,3741,618,Compound 614,199.170425,0.698493,0.914036,-1,155.14,13.305032,2.963187e+03
3742,3742,618,Compound 614,199.170425,0.698493,0.914036,-1,173.48,25.549013,2.576380e+03

In [3]:
data = data[(data["Normalized Intensity"] != float("inf")) & (data["Normalized Intensity"] > 2000)]
data

,Unnamed: 0,Unnamed: 0.1,Name,mz,rt_start,rt_end,Charge,Product mz,CE,Normalized Intensity
0,0,4,Compound 5,162.112534,5.335723,5.680650,1,103.04,16.397564,5.217794e+06
1,1,4,Compound 5,162.112534,5.335723,5.680650,1,60.08,16.397564,4.085165e+06
2,2,4,Compound 5,162.112534,5.335723,5.680650,1,85.03,16.397564,2.510912e+06
3,3,4,Compound 5,162.112534,5.335723,5.680650,1,102.09,16.397564,1.756255e+06
4,4,4,Compound 5,162.112534,5.335723,5.680650,1,58.07,36.804199,1.659919e+06
...,...,...,...,...,...,...,...,...,...,...
3738,3738,618,Compound 614,199.170425,0.698493,0.914036,-1,119.05,21.467686,6.778207e+04
3739,3739,618,Compound 614,199.170425,0.698493,0.914036,-1,93.03,37.792993,8.675127e+03
3740,3740,618,Compound 614,199.170425,0.698493,0.914036,-1,79.96,29.630339,4.840894e+03
3741,3741,618,Compound 614,199.170425,0.698493,0.914036,-1,155.14,13.305032,2.963187e+03
3742,3742,618,Compound 614,199.170425,0.698493,0.914036,-1,173.48,25.549013,2.576380e+03

In [4]:
cpds = list(set(data["Name"].values))
print(len(cpds))

629

In [5]:
toKeep = []
annotation = {}
for cpd in cpds:
    filt = data[data["Name"] == cpd]
    filt.sort_values(by="Normalized Intensity",ascending=False)
    charge = filt.at[filt.index.values[0],"Charge"]
    filt = filt[filt["Charge"] == charge]
    toKeep += list(filt.index.values)
    mapper = ["Quant","Qual 1","Qual 2","Qual 3","Qual 4"]
    for ind,lab in zip(filt.index.values,mapper[:len(filt)]):
        annotation[ind] = {"Ion type":lab}

In [6]:
data = data.loc[toKeep,:]
data = pd.concat((data,pd.DataFrame.from_dict(annotation,orient="index")),axis=1,ignore_index=False)
data

,Unnamed: 0,Unnamed: 0.1,Name,mz,rt_start,rt_end,Charge,Product mz,CE,Normalized Intensity,Ion type
0,0,4,Compound 5,162.112534,5.335723,5.680650,1,103.04,16.397564,5.217794e+06,Quant
1,1,4,Compound 5,162.112534,5.335723,5.680650,1,60.08,16.397564,4.085165e+06,Qual 1
2,2,4,Compound 5,162.112534,5.335723,5.680650,1,85.03,16.397564,2.510912e+06,Qual 2
3,3,4,Compound 5,162.112534,5.335723,5.680650,1,102.09,16.397564,1.756255e+06,Qual 3
4,4,4,Compound 5,162.112534,5.335723,5.680650,1,58.07,36.804199,1.659919e+06,Qual 4
...,...,...,...,...,...,...,...,...,...,...,...
3738,3738,618,Compound 614,199.170425,0.698493,0.914036,-1,119.05,21.467686,6.778207e+04,Quant
3739,3739,618,Compound 614,199.170425,0.698493,0.914036,-1,93.03,37.792993,8.675127e+03,Qual 1
3740,3740,618,Compound 614,199.170425,0.698493,0.914036,-1,79.96,29.630339,4.840894e+03,Qual 2
3741,3741,618,Compound 614,199.170425,0.698493,0.914036,-1,155.14,13.305032,2.963187e+03,Qual 3
3742,3742,618,Compound 614,199.170425,0.698493,0.914036,-1,173.48,25.549013,2.576380e+03,Qual 4

In [7]:
compoundInfo = {}
for index,row in data.iterrows():
    compoundInfo[row["Name"]] = {"mz":row["mz"],"Charge":row["Charge"],"rt":np.mean([row["rt_start"],row["rt_end"]])}

In [8]:
mzTol = 5
rtTol = .33
badCpds = []

for cpd in compoundInfo:
    good = True
    for cpd2 in compoundInfo:
        if cpd != cpd2 and cpd2 not in badCpds:
            if compoundInfo[cpd]["Charge"] == compoundInfo[cpd2]["Charge"]:
                if abs(compoundInfo[cpd]["rt"] - compoundInfo[cpd2]["rt"]) < rtTol:
                    if 1e6 * np.abs(compoundInfo[cpd]["mz"] - compoundInfo[cpd2]["mz"])/compoundInfo[cpd]["mz"] < mzTol:
                        good = False
                        break
    if not good:
        badCpds.append(cpd)

In [9]:
print(badCpds)

['Compound 20', 'Compound 212', 'Compound 582', 'Compound 588', 'Compound 589', 'Compound 675', 'Compound 714', 'Compound 750']

In [10]:
toDrop = []
for cpd in badCpds:
    filt = data[data["Name"] == cpd]
    toDrop += list(filt.index.values)
data = data.drop(toDrop)
data.sort_values(by="Name")
data

,Unnamed: 0,Unnamed: 0.1,Name,mz,rt_start,rt_end,Charge,Product mz,CE,Normalized Intensity,Ion type
0,0,4,Compound 5,162.112534,5.335723,5.680650,1,103.04,16.397564,5.217794e+06,Quant
1,1,4,Compound 5,162.112534,5.335723,5.680650,1,60.08,16.397564,4.085165e+06,Qual 1
2,2,4,Compound 5,162.112534,5.335723,5.680650,1,85.03,16.397564,2.510912e+06,Qual 2
3,3,4,Compound 5,162.112534,5.335723,5.680650,1,102.09,16.397564,1.756255e+06,Qual 3
4,4,4,Compound 5,162.112534,5.335723,5.680650,1,58.07,36.804199,1.659919e+06,Qual 4
...,...,...,...,...,...,...,...,...,...,...,...
3738,3738,618,Compound 614,199.170425,0.698493,0.914036,-1,119.05,21.467686,6.778207e+04,Quant
3739,3739,618,Compound 614,199.170425,0.698493,0.914036,-1,93.03,37.792993,8.675127e+03,Qual 1
3740,3740,618,Compound 614,199.170425,0.698493,0.914036,-1,79.96,29.630339,4.840894e+03,Qual 2
3741,3741,618,Compound 614,199.170425,0.698493,0.914036,-1,155.14,13.305032,2.963187e+03,Qual 3
3742,3742,618,Compound 614,199.170425,0.698493,0.914036,-1,173.48,25.549013,2.576380e+03,Qual 4

In [11]:
data.to_csv("../data/IDX/AX_stab_pool/generated_SRM_table_filtered.csv")